### ISSUE TITLE
Android: AOSP Browser vs Chrome

### ISSUE THREAD

**Issue by gaia** [ahand/mobileesp#1]
Does mobileesp include a way to tell android users on the stock android browser from android users using Chrome?

Thanks

**Comment by ahand** [comment]
Hi, Gala --

It's outside the scope of MobileESP to distinguish between browsers generally. (Except where certain browsers misbehave, like Opera...) 

There is a general DetectAndroid() method, plus several others. Check the API for more info. 

One of the challenges with sniffing useragent strings on Android is that the handset manufacturer can set the string as desired. Most make good decisions most of the time, but some manufacturers make very bad decisions. 

Good luck!
Anthony
