### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ThaDafinser** [ahand/mobileesp#14]
is this project still alive?

//cc @ahand

**Comment by ahand** [comment]
Yes, it's still maintained. I haven't seen a need to update it in awhile. The useragent strings for the major platforms haven't changed lately. And the up-and-coming mobile platforms like Sailfish and Tizen haven't really been going anywhere lately... But anyways, we're keeping an eye on the space. 

If you see a need for an update for any reason, please let us know!

Anthony
