### ISSUE TITLE
 iOS 13 iPad device detection issue

### ISSUE THREAD

**Issue by NitaKokat** [ahand/mobileesp#21]

**Comment by ahand** [comment]
Tested on an iPad Air (newest generation) in Feb 2021. 

With the Google Chrome browser: the iPad detect works as expected. Good. 

With the Safari browser: the iPad detect does NOT work as expected. It returns "false." 

Unfortunately, after reviewing the user agent string and other meta-data, it looks like Apple has decided to notify web publishers that the iPad should be treated like a desktop/laptop Mac computer. The user agent string looks just like a desktop Mac computer string. 

Apple removed the "ipad" and "mobile" tokens. This means that there is nothing unique in the user agent string that we can latch onto to distinguish an iPad from a desktop/laptop computer. 

This appears to be working "as design" by Apple. Sorry!
